### ISSUE TITLE
counting-numbers.tsx displays negative count when switching tabs

### ISSUE THREAD

**Issue by tautastic** [steven-tey/precedent#28]
### The issue:

![Screenshot 2023-03-07 at 22-29-17 Precedent - Building blocks for your Next js project](https://user-images.githubusercontent.com/91988666/223557312-4e6736f2-e013-4ac9-8766-25449ea2de97.png)

#### Steps to reproduce:

Open [the precedent website](https://precedent.dev/) and quickly switch to another tab while the counter is still counting up. Wait for a few seconds and then go back to the precedent tab.

I'm not familiar with the codebase but I'll try to figure out how this happens.

**Comment by add1609** [comment]
The problem occurs when `const progress = timePassed / duration;` is bigger than `1`. This can happen when switching tabs because the timestamps passed to `animateCount` by `requestAnimationFrame` kept growing while the client was on another tab.

The problem can be fixed inside the `easeOutQuad` function by ensuring that `t/d` is always less or equal to `d`.

```ts
const easeOutQuad = (t: number, b: number, c: number, d: number) => {
  t = t > d ? d : t / d;
  return Math.round(-c * t * (t - 2) + b);
};
```

**Comment by steven-tey** [comment]
You, sir, are a freaking legend! Thank you for the PR – it works like a charm!
